#!/bin/bash

#GIVES THE IP ADDRESS WHICH IS ACCESSING THE APACHE SERVER FOR THE MAXIMUM TIME 
#uniq -c returns the uniq element along with the number of occurance of them 

cat access.log | awk '{print $1}' | sort | uniq -c | sort -n > outputfile 

x= $( cat outputfile | awk '{print $2}' | tail -1 )
echo "$x is the IP   accessing the apache server for the maximum time "
